Repository RedHatInsights/approval-api, pull requests merged in 2019-11, with the labels that each got.

#208 Sprint 41 merge to stable
  .travis.yml
  Gemfile
  Jenkinsfile-smoke.groovy
  app/controllers/api/v1x0/actions_controller.rb
  app/controllers/api/v1x0/mixins/index_mixin.rb
  app/controllers/api/v1x0/requests_controller.rb
  app/controllers/api/v1x0/workflows_controller.rb
  app/controllers/application_controller.rb
  app/models/concerns/approval_states.rb
  app/models/request.rb
  app/models/request_context.rb
  app/models/tag_link.rb
  app/models/workflow.rb
  app/services/add_remote_tags.rb
  app/services/get_remote_tags.rb
  app/services/remote_tagging_service.rb
  app/services/request_create_service.rb
  app/services/workflow_find_service.rb
  app/services/workflow_link_service.rb
  app/services/workflow_unlink_service.rb
  config/routes.rb
  db/migrate/20191010102743_create_tag_links.rb
  db/migrate/20191011161512_change_tag_links_index.rb
  db/migrate/20191014102030_add_sequence_to_workflows.rb
  db/migrate/20191018141212_add_parent_id_to_requests.rb
  db/migrate/20191018142121_create_request_contexts.rb
  db/schema.rb
  public/doc/openapi-3-v1.0.0.json
  spec/controllers/v1.0/actions_controller_spec.rb
  spec/controllers/v1.0/graphql_controller_spec.rb
  spec/controllers/v1.0/requests_controller_spec.rb
  spec/controllers/v1.0/stages_controller_spec.rb
  spec/controllers/v1.0/workflows_controller_spec.rb
  spec/factories/requests.rb
  spec/factories/workflows.rb
  spec/models/request_spec.rb
  spec/models/tag_link_spec.rb
  spec/models/workflow_spec.rb
  spec/services/add_remote_tags_spec.rb
  spec/services/get_remote_tags_spec.rb
  spec/services/request_create_service_spec.rb
  spec/services/workflow_find_service_spec.rb
  spec/services/workflow_link_service_spec.rb
  spec/spec_helper.rb
Labels: stable

#204 Remove stage model/service and associate actions to request
  app/controllers/api/v1x0/stages_controller.rb
  app/controllers/api/v1x0/workflows_controller.rb
  app/models/action.rb
  app/models/request.rb
  app/models/stage.rb
  app/services/stage_update_service.rb
  db/migrate/20191104103543_add_request_id_to_actions.rb
  db/migrate/20191104161718_add_more_columns_to_requests.rb
  db/migrate/20191105111213_drop_stages.rb
  db/schema.rb
  spec/controllers/v1.0/actions_controller_spec.rb
  spec/controllers/v1.0/graphql_controller_spec.rb
  spec/controllers/v1.0/requests_controller_spec.rb
  spec/controllers/v1.0/stages_controller_spec.rb
  spec/factories/stages.rb
  spec/models/action_spec.rb
  spec/models/request_spec.rb
  spec/models/stage_spec.rb
  spec/services/action_create_service_spec.rb
  spec/services/event_service_spec.rb
  spec/services/jbpm_process_service_spec.rb
  spec/services/stage_update_service_spec.rb
Labels: unmergeable

#218 Fix a typo and add spec tests
  app/models/request.rb
  spec/models/request_spec.rb
Labels: bug
