Repository RedHatInsights/approval-api, pull requests merged in 2019-03, with the labels that each got.

#53 Adds pagination support
  app/controllers/api/v0/admins_controller.rb
  app/controllers/api/v0/mixins/requester_operations_mixin.rb
  app/controllers/api/v0/mixins/user_operations_mixin.rb
  app/controllers/api/v0/requesters_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/api/v0x1/actions_controller.rb
  app/controllers/api/v0x1/groups_controller.rb
  app/controllers/api/v0x1/mixins/index_mixin.rb
  app/controllers/api/v0x1/requests_controller.rb
  app/controllers/api/v0x1/stages_controller.rb
  app/controllers/api/v0x1/templates_controller.rb
  app/controllers/api/v0x1/users_controller.rb
  app/controllers/api/v0x1/workflows_controller.rb
  app/controllers/mixins/requester_operations_mixin.rb
  app/controllers/mixins/user_operations_mixin.rb
  public/approval/v0.1.0/openapi.json
  spec/requests/v0.1/groups_spec.rb
  spec/requests/v0.1/requests_spec.rb
  spec/requests/v0.1/stages_spec.rb
  spec/requests/v0.1/templates_spec.rb
  spec/requests/v0.1/users_spec.rb
  spec/requests/v0.1/workflows_spec.rb
Labels: enhancement

#54 Set current request context and set tenant from header
  app/controllers/application_controller.rb
  lib/exceptions.rb
  spec/models/tenant_spec.rb
  spec/requests/v0.0/actions_spec.rb
  spec/requests/v0.0/groups_spec.rb
  spec/requests/v0.0/requests_spec.rb
  spec/requests/v0.0/stages_spec.rb
  spec/requests/v0.0/templates_spec.rb
  spec/requests/v0.0/users_spec.rb
  spec/requests/v0.0/workflows_spec.rb
  spec/requests/v0.1/actions_spec.rb
  spec/requests/v0.1/groups_spec.rb
  spec/requests/v0.1/requests_spec.rb
  spec/requests/v0.1/stages_spec.rb
  spec/requests/v0.1/templates_spec.rb
  spec/requests/v0.1/users_spec.rb
  spec/requests/v0.1/workflows_spec.rb
  spec/support/request_spec_helper.rb
Labels: enhancement, unmergeable

#51 Switch to rbac service to get user and group
  Gemfile
  app/models/group.rb
  app/models/stage.rb
  app/models/user.rb
  app/models/usergroup.rb
  app/models/workflow.rb
  app/models/workflowgroup.rb
  app/services/action_create_service.rb
  app/services/event_service.rb
  app/services/group_operation_service.rb
  app/services/request_create_service.rb
  config/initializers/load_extensions.rb
  config/routes.rb
  db/migrate/20190225153612_drop_groups_and_users.rb
  db/schema.rb
  lib/exceptions.rb
  lib/rbac/service.rb
  public/approval/v0.0.1/openapi.json
  public/approval/v0.1.0/openapi.json
  spec/controllers/v1/groups_controller_spec.rb
  spec/controllers/v1/users_controller_spec.rb
  spec/factories/groups.rb
  spec/factories/stages.rb
  spec/factories/users.rb
  spec/factories/workflows.rb
  spec/models/group_spec.rb
  spec/models/stage_spec.rb
  spec/models/user_spec.rb
  spec/models/workflow_spec.rb
  spec/requests/v0.0/actions_spec.rb
  spec/requests/v0.0/groups_spec.rb
  spec/requests/v0.0/stages_spec.rb
  spec/requests/v0.0/users_spec.rb
  spec/requests/v0.0/workflows_spec.rb
  spec/requests/v0.1/actions_spec.rb
  spec/requests/v0.1/groups_spec.rb
  spec/requests/v0.1/stages_spec.rb
  spec/requests/v0.1/users_spec.rb
  spec/requests/v0.1/workflows_spec.rb
  spec/services/event_service_spec.rb
  spec/services/request_create_service_spec.rb
  spec/services/workflow_create_service_spec.rb
Labels: enhancement, unmergeable

#60 Don't eager load code on boot
  config/application.rb
  config/environments/production.rb
Labels: bug

#68 Added basic authentication scheme back
  public/approval/v0.1.0/openapi.json
Labels: bug

#67 Start or signal a business process through kie_client
  Gemfile
  app/models/workflow.rb
  app/services/jbpm_process_service.rb
  app/services/request_create_service.rb
  app/services/stage_update_service.rb
  config/initializers/load_extensions.rb
  lib/exceptions.rb
  lib/kie/service.rb
  spec/services/action_create_service_spec.rb
  spec/services/jbpm_process_service_spec.rb
  spec/services/request_create_service_spec.rb
  spec/services/stage_update_service_spec.rb
Labels: enhancement

#73 Changed version to v1
  app/controllers/api/v1x0/actions_controller.rb
  app/controllers/api/v1x0/groups_controller.rb
  app/controllers/api/v1x0/mixins/index_mixin.rb
  app/controllers/api/v1x0/requests_controller.rb
  app/controllers/api/v1x0/stages_controller.rb
  app/controllers/api/v1x0/templates_controller.rb
  app/controllers/api/v1x0/users_controller.rb
  app/controllers/api/v1x0/workflows_controller.rb
  config/initializers/swagger_ui_engine.rb
  config/routes.rb
  public/approval/v1.0/openapi.json
  spec/controllers/v1.0/actions_controller_spec.rb
  spec/controllers/v1.0/requests_controller_spec.rb
  spec/controllers/v1.0/stages_controller_spec.rb
  spec/controllers/v1.0/templates_controller_spec.rb
  spec/controllers/v1.0/workflows_controller_spec.rb
  spec/controllers/v1/actions_controller_spec.rb
  spec/controllers/v1/requests_controller_spec.rb
  spec/controllers/v1/stages_controller_spec.rb
  spec/controllers/v1/templates_controller_spec.rb
  spec/controllers/v1/workflows_controller_spec.rb
  spec/requests/v1.0/actions_spec.rb
  spec/requests/v1.0/requests_spec.rb
  spec/requests/v1.0/stages_spec.rb
  spec/requests/v1.0/templates_spec.rb
  spec/requests/v1.0/workflows_spec.rb
  spec/support/request_spec_helper.rb
  spec/swagger_spec.rb
Labels: enhancement

#74 Add a random id column to stages table
  app/services/request_create_service.rb
  app/services/stage_update_service.rb
  db/migrate/20190329151023_add_random_access_key_to_stages.rb
  db/schema.rb
  spec/services/request_create_service_spec.rb
Labels: enhancement

#77 Removed api_auth_key
  public/approval/v1.0/openapi.json
Labels: bug

#80 StrongParameters with hash values have to be at the end
  app/controllers/api/v1x0/requests_controller.rb
  spec/requests/v1.0/requests_spec.rb
Labels: bug
