Repository RedHatInsights/approval-api, pull requests merged in 2020-07, with the labels that each got.

#380 Sprint 56 merge to stable
  .travis_scripts/openapi-validator.sh
  app/models/workflow.rb
  spec/models/workflow_spec.rb
Labels: stable

#383 Add internal_sequence to workflow
  app/controllers/api/v1x2/workflows_controller.rb
  app/models/workflow.rb
  app/policies/workflow_policy.rb
  app/services/sequence_update_service.rb
  config/routes/v1x2.rb
  db/migrate/20200226115345_delete_always_approve_from_workflows.rb
  db/migrate/20200630145352_add_internal_sequences_to_workflow.rb
  db/schema.rb
  public/doc/openapi-3-v1.2.json
  spec/controllers/v1.2/workflows_controller_spec.rb
  spec/models/workflow_spec.rb
  spec/policies/workflow_policy_spec.rb
Labels: sql migration

#384 Sprint 57 merge to stable
  .travis.yml
  .travis_scripts/openapi-validator.sh
  app/controllers/api/v1x2/workflows_controller.rb
  app/models/workflow.rb
  app/policies/workflow_policy.rb
  app/services/sequence_update_service.rb
  app/services/workflow_delete_service.rb
  config/routes/v1x2.rb
  db/migrate/20200226115345_delete_always_approve_from_workflows.rb
  db/migrate/20200630145352_add_internal_sequences_to_workflow.rb
  db/schema.rb
  public/doc/openapi-3-v1.2.json
  spec/controllers/v1.2/workflows_controller_spec.rb
  spec/models/workflow_spec.rb
  spec/policies/workflow_policy_spec.rb
  spec/services/workflow_delete_service_spec.rb
Labels: sql migration, stable
