Repository RedHatInsights/approval-api, pull requests merged in 2020-06, with the labels that each got.

#372 Fix mis-spelled error class name
  app/services/workflow_create_service.rb
  app/services/workflow_delete_service.rb
  app/services/workflow_update_service.rb
  config/initializers/custom_exception_mappings.rb
  spec/config/initializers/custom_exception_mappings_spec.rb
  spec/controllers/v1.2/workflows_controller_spec.rb
Labels: bug

#371 [Stable] Prevent workflow sequence from becoming negative
  app/controllers/api/v1x2/workflows_controller.rb
  app/models/workflow.rb
  app/services/workflow_create_service.rb
  app/services/workflow_delete_service.rb
  app/services/workflow_update_service.rb
  config/initializers/custom_exception_mappings.rb
  lib/exceptions.rb
  spec/config/initializers/custom_exception_mappings_spec.rb
  spec/controllers/v1.2/workflows_controller_spec.rb
  spec/services/workflow_delete_service_spec.rb
Labels: stable

#373 Sprint 54 merge to stable
  Gemfile
  app/controllers/api/v1x2/stageaction/result.html.erb
  app/controllers/api/v1x2/stageaction/show.html.erb
  app/services/remote_tagging_service.rb
  config/initializers/custom_exception_mappings.rb
  lib/exceptions.rb
  lib/kie/service.rb
  spec/lib/kie/service_spec.rb
  spec/services/add_remote_tags_spec.rb
  spec/services/delete_remote_tags_spec.rb
  spec/services/get_remote_tags_spec.rb
  spec/support/tag_resources_shared_context.rb
Labels: dependencies, stable

#378 Sprint 55 merge to stable
  .gitattributes
  app/models/workflow.rb
  app/policies/workflow_policy.rb
  app/services/event_service.rb
  app/services/workflow_create_service.rb
  app/services/workflow_delete_service.rb
  app/services/workflow_update_service.rb
  config/initializers/custom_exception_mappings.rb
  public/doc/openapi-3-v1.2.json
  spec/controllers/v1.2/workflows_controller_spec.rb
  spec/models/workflow_spec.rb
  spec/open_api_spec.rb
  spec/policies/workflow_policy_spec.rb
  spec/services/event_service_spec.rb
  spec/support/random_words_spec_helper.rb
  spec/swagger_spec.rb
Labels: stable
