Repository RedHatInsights/approval-api, pull requests merged in 2020-01, with the labels that each got.

#251 Fix Workflow#external_processing? and #external_signal?
  app/models/workflow.rb
  spec/models/workflow_spec.rb
Labels: bug

#256 Sprint 43 Hotfix #1 merge to stable
  Gemfile
  README.md
  app/models/workflow.rb
  app/services/request_create_service.rb
  spec/models/request_spec.rb
  spec/models/template_spec.rb
  spec/models/workflow_spec.rb
  spec/services/request_create_service_spec.rb
Labels: stable

#261 Sprint 44 merge to stable
  app/controllers/api/v1/mixins/rbac_mixin.rb
  app/controllers/application_controller.rb
  app/services/event_service.rb
  docker-assets/run_rails_server
  spec/controllers/v1.0/graphql_controller_spec.rb
  spec/controllers/v1.0/root_controller_spec.rb
Labels: stable

#262 Approval screen enhancements
  app/controllers/api/v1/stageaction/_footer.html.erb
  app/controllers/api/v1/stageaction/_header.html.erb
  app/controllers/api/v1/stageaction/_request.html.erb
  app/controllers/api/v1/stageaction/result.html.erb
  app/controllers/api/v1/stageaction/show.html.erb
  public/logo.svg
  public/patternfly.css
Labels: enhancement
